# Generated by Django 4.1 on 2022-08-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.TextField()),
                ('customer_surname', models.TextField()),
                ('customer_dni', models.TextField(db_column='customer_DNI')),
                ('dob', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.TextField()),
                ('number', models.IntegerField()),
                ('city', models.TextField()),
                ('province', models.TextField()),
                ('country', models.TextField()),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.TextField()),
                ('employee_surname', models.TextField()),
                ('employee_hire_date', models.TextField()),
                ('employee_dni', models.TextField(db_column='employee_DNI')),
                ('branch_id', models.IntegerField()),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_number', models.BinaryField()),
                ('branch_name', models.TextField()),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('customer_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.TextField(unique=True)),
                ('debit_card', models.TextField()),
                ('credit_card', models.TextField()),
                ('current_account', models.TextField()),
                ('checkbook_amount', models.IntegerField()),
                ('box_dollar', models.TextField(blank=True, null=True)),
                ('box_peso', models.TextField(blank=True, null=True)),
                ('withdraw_daily_max', models.IntegerField(blank=True, null=True)),
                ('transfer_comission', models.IntegerField(blank=True, null=True)),
                ('max_travel_reception', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_cliente',
                'managed': False,
            },
        ),
    ]
